export const payments = [
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "a@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "b@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "c@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "e@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "f@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "g@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "h@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "i@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "j@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "k@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "l@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "m@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "n@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "o@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "p@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "q@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "r@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "s@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "t@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "u@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "v@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "w@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "x@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "y@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "z@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "a@example.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "b@example.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "c@example.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "d@example.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "e@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "f@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "g@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "h@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "i@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "j@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "k@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "l@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "m@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "o@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "p@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "q@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "r@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "t@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "u@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "v@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "w@gmail.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "x@gmail.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "y@gmail.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "z@gmail.com",
    },
    {
        id: "728ed52f",
        amount: 100,
        status: "pending",
        email: "a@example.com",
    },
    {
        id: "489e1d42",
        amount: 125,
        status: "processing",
        email: "b@example.com",
    },
    {
        id: "1",
        amount: 125,
        status: "processing",
        email: "c@example.com",
    },
    {
        id: "2",
        amount: 125,
        status: "processing",
        email: "d@example.com",
    },
    {
        id: "3",
        amount: 125,
        status: "processing",
        email: "e@example.com",
    },
    {
        id: "4",
        amount: 125,
        status: "processing",
        email: "f@example.com",
    },
    {
        id: "5",
        amount: 125,
        status: "processing",
        email: "g@example.com",
    },
    {
        id: "6",
        amount: 125,
        status: "processing",
        email: "h@example.com",
    },
    {
        id: "7",
        amount: 125,
        status: "processing",
        email: "i@example.com",
    },
    {
        id: "8",
        amount: 125,
        status: "processing",
        email: "j@example.com",
    },
    {
        id: "9",
        amount: 125,
        status: "processing",
        email: "k@example.com",
    },
]